# Generated by Django 2.0.6 on 2018-08-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='base_experience',
            field=models.IntegerField(default=0),
        ),
    ]
