# Generated by Django 2.0.6 on 2018-08-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_hero_base_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='quest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quests.Quest'),
        ),
    ]
