# Generated by Django 2.0.6 on 2018-08-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_hero_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quests.Quest'),
        ),
    ]
