# Generated by Django 2.0.6 on 2018-08-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_auto_20180818_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='quest',
        ),
        migrations.AddField(
            model_name='hero',
            name='quests',
            field=models.ManyToManyField(to='quests.Quest'),
        ),
    ]
