# Generated by Django 2.0.6 on 2018-08-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_auto_20180818_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='quests',
        ),
        migrations.AddField(
            model_name='hero',
            name='quests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quests.Quest'),
            preserve_default=False,
        ),
    ]
