# Generated by Django 2.0.6 on 2018-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0007_auto_20180818_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='footer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
