# Generated by Django 2.0.6 on 2018-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_quest_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='quests',
        ),
        migrations.AddField(
            model_name='hero',
            name='quests',
            field=models.ManyToManyField(to='quests.Quest'),
        ),
    ]
