# Generated by Django 2.0.6 on 2018-08-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0009_auto_20180818_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='base_experience',
            new_name='exp',
        ),
    ]
